import type { CSSProperties, ReactNode } from 'react';
import type { DesignSystem, Page, SlideMeta } from '@open-slide/core';

type FontKind='serif'|'sans'|'mono';
type Theme = { slug:string; title:string; short:string; source:string; best:string; tone:string; bg:string; fg:string; muted:string; accent:string; card:string; border:string; font:FontKind; pattern:string };
const t = {"slug": "od-social-carousel-suite", "title": "OD Social Carousel Suite", "short": "Social Carousel", "source": "Open Design: skills/social-carousel", "best": "社媒卡片 / 小红书组图 / 观点拆解", "tone": "明亮卡片、强标题、连续阅读", "bg": "#fff7ed", "fg": "#23140b", "muted": "#8b5e34", "accent": "#f97316", "card": "#fffaf3", "border": "#fed7aa", "font": "sans", "pattern": "carousel"} as Theme;
const serif='Georgia, "Noto Serif CJK SC", "Source Han Serif SC", "Songti SC", serif';
const sans='Inter, "PingFang SC", "Microsoft YaHei", system-ui, sans-serif';
const mono='"JetBrains Mono", ui-monospace, SFMono-Regular, Menlo, Consolas, monospace';
const font=()=>t.font==='serif'?serif:t.font==='mono'?mono:sans;
const rgba=(h:string,a:number)=>{const x=h.replace('#','');const n=parseInt(x.length===3?x.split('').map(c=>c+c).join(''):x,16);return `rgba(${(n>>16)&255}, ${(n>>8)&255}, ${n&255}, ${a})`;};
const dark=['finance','motion','blueprint','graph','terminal'].includes(t.pattern);
const base:CSSProperties={width:'100%',height:'100%',position:'relative',overflow:'hidden',boxSizing:'border-box',background:t.bg,color:t.fg,fontFamily:font()};

export const design: DesignSystem = { palette:{bg:t.bg,text:t.fg,accent:t.accent}, fonts:{display:font(),body:font()}, typeScale:{hero:108,body:30}, radius:30 };
export const meta: SlideMeta = { title:t.title, description:`${t.short} 独立 Open-Slide 模板套件：20 个常见 PPT page templates。` };
export const notes = [`${t.short} standalone album`, `Source: ${t.source}`, '只移植 Open Design 视觉语言，不复制 runtime。'];

const css=`@keyframes rise{from{opacity:0;transform:translateY(26px)}to{opacity:1;transform:translateY(0)}}@keyframes sweep{0%{transform:translateX(-120%)}100%{transform:translateX(120%)}}@keyframes glow{0%,100%{opacity:.45}50%{opacity:1}}.r{animation:rise .62s cubic-bezier(.2,.9,.2,1) both}.card{border-radius:30px;border:1.5px solid ${t.border};background:${t.card};box-shadow:0 28px 80px ${rgba(dark?'#000000':t.fg,dark?.28:.08)}}.tag{display:inline-flex;border-radius:999px;padding:10px 16px;font:850 17px/1 ${mono};letter-spacing:.1em;text-transform:uppercase}`;
function Shell({n,kind,children}:{n:string;kind:string;children:ReactNode}){return <div style={base}><style>{css}</style><Decor/><div style={{position:'absolute',inset:52,border:`1px solid ${rgba(t.fg,dark?.15:.12)}`,borderRadius:38,pointerEvents:'none'}}/>{children}<div style={{position:'absolute',left:86,bottom:64,color:t.muted,font:`18px ${mono}`,letterSpacing:'.08em'}}>{n} · {kind}</div><div style={{position:'absolute',right:86,bottom:64,color:t.muted,font:`18px ${mono}`}}>{t.short} · OD → Open Slide</div></div>}
function Tag({children}:{children:ReactNode}){return <span className="tag" style={{background:rgba(t.accent,dark?.18:.14),color:t.accent,border:`1px solid ${rgba(t.accent,.34)}`}}>{children}</span>}
function H({children,size=90,style}:{children:ReactNode;size?:number;style?:CSSProperties}){return <h1 className="r" style={{margin:0,fontSize:size,lineHeight:.94,letterSpacing:'-.067em',fontWeight:900,color:t.fg,...style}}>{children}</h1>}
function P({children,style}:{children:ReactNode;style?:CSSProperties}){return <p className="r" style={{margin:0,color:t.muted,fontSize:30,lineHeight:1.38,...style}}>{children}</p>}
function Card({children,style}:{children:ReactNode;style?:CSSProperties}){return <div className="card r" style={{padding:32,...style}}>{children}</div>}
function Decor(){
  if(t.pattern==='blueprint') return <div style={{position:'absolute',inset:0,backgroundImage:`linear-gradient(${rgba(t.accent,.13)} 1px, transparent 1px),linear-gradient(90deg,${rgba(t.accent,.13)} 1px, transparent 1px)`,backgroundSize:'56px 56px'}}/>;
  if(t.pattern==='terminal') return <div style={{position:'absolute',inset:0,background:`radial-gradient(circle at 78% 18%, ${rgba(t.accent,.22)}, transparent 34%), repeating-linear-gradient(0deg, transparent 0 7px, ${rgba(t.accent,.04)} 8px)`}}/>;
  if(t.pattern==='magazine') return <div style={{position:'absolute',right:-120,top:80,width:620,height:620,borderRadius:999,background:rgba(t.accent,.08),border:`2px solid ${rgba(t.accent,.18)}`}}/>;
  return <div style={{position:'absolute',right:-150,top:-150,width:540,height:540,borderRadius:999,background:`radial-gradient(circle, ${rgba(t.accent,dark?.28:.14)}, transparent 68%)`}}/>;
}

const formats=['Cover','Agenda','Problem','Framework','Content','Metrics','Timeline','Diagram','Closing'];
const Cover:Page=()=> <Shell n="01" kind="Cover"><div style={{position:'absolute',inset:'112px 126px 126px',display:'grid',gridTemplateColumns:'1.03fr .97fr',gap:54,alignItems:'center'}}><div><Tag>{t.source}</Tag><H size={122} style={{marginTop:34,maxWidth:1000}}>{t.short}</H><P style={{marginTop:32,fontSize:36,maxWidth:900}}>{t.best}</P><div style={{marginTop:42,display:'flex',gap:14,flexWrap:'wrap'}}>{['20 pages','template pack','React primitives'].map(x=><Tag key={x}>{x}</Tag>)}</div></div><HeroVisual/></div></Shell>;
const Agenda:Page=()=> <Shell n="02" kind="Agenda"><div style={{position:'absolute',inset:'104px 126px 126px'}}><Tag>template coverage</Tag><H size={82} style={{marginTop:28,maxWidth:1180}}>前九页保留基础叙事，后十一页扩展常见子页面。</H><div style={{marginTop:46,display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:20}}>{formats.map((x,i)=><Card key={x} style={{minHeight:142,animationDelay:`${i*35}ms`}}><div style={{font:`21px ${mono}`,color:t.accent}}>0{i+1}</div><div style={{marginTop:22,fontSize:34,fontWeight:880}}>{x}</div></Card>)}</div></div></Shell>;
const Problem:Page=()=> <Shell n="03" kind="Problem / Context"><div style={{position:'absolute',inset:'104px 126px 126px',display:'grid',gridTemplateColumns:'.9fr 1.1fr',gap:46,alignItems:'center'}}><div><Tag>context</Tag><H size={84} style={{marginTop:30}}>这套适合表达：{t.best.split(' / ')[0]}。</H><P style={{marginTop:28}}>{t.tone}。模板提供固定叙事节奏，避免 Agent 每次重新发明版式。</P></div><ProblemVisual/></div></Shell>;
const Framework:Page=()=> <Shell n="04" kind="Framework"><div style={{position:'absolute',inset:'104px 126px 126px'}}><Tag>framework</Tag><H size={80} style={{marginTop:28,maxWidth:1240}}>从 OD 借三样：气质、组件秩序、页面原型。</H><div style={{marginTop:56,display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:24}}>{[['01','Visual Tokens','色彩、字体、边框、密度。'],['02','Page Recipe','一页一个任务，结构先行。'],['03','Production Gate','构建 + 截图 + contact sheet。']].map(([a,b,c],i)=><Card key={b} style={{minHeight:330,animationDelay:`${i*70}ms`}}><div style={{font:`22px ${mono}`,color:t.accent}}>{a}</div><h2 style={{fontSize:48,lineHeight:1.05,margin:'34px 0 18px',letterSpacing:'-.05em'}}>{b}</h2><p style={{fontSize:26,lineHeight:1.38,color:t.muted,margin:0}}>{c}</p></Card>)}</div></div></Shell>;
const Content:Page=()=> <Shell n="05" kind="Content"><div style={{position:'absolute',inset:'104px 126px 126px',display:'grid',gridTemplateColumns:'1fr 1fr',gap:42,alignItems:'center'}}><div><Tag>content slide</Tag><H size={82} style={{marginTop:30}}>左侧主张，右侧展开。</H><P style={{marginTop:28}}>保持成熟 deck 的节奏：强标题、少文本、可扫读的证据层。</P></div><div style={{display:'grid',gap:18}}>{['先抛结论。','给三条证据。','用强调色标出路径。'].map((x,i)=><Card key={x} style={{display:'grid',gridTemplateColumns:'72px 1fr',gap:18,alignItems:'center'}}><div style={{font:`28px ${mono}`,color:t.accent}}>0{i+1}</div><div style={{fontSize:32,lineHeight:1.25,color:t.fg,fontWeight:780}}>{x}</div></Card>)}</div></div></Shell>;
const Metrics:Page=()=> <Shell n="06" kind="Metrics / Data"><div style={{position:'absolute',inset:'104px 126px 126px',display:'grid',gridTemplateColumns:'.85fr 1.15fr',gap:44,alignItems:'center'}}><div><Tag>metrics</Tag><H size={80} style={{marginTop:28}}>数据页要给答案，不只给数字。</H><P style={{marginTop:26}}>指标、趋势、风险、动作，放在同一屏闭环。</P></div><div><MetricRow/><div style={{height:260,marginTop:24}}><Bars/></div></div></div></Shell>;
const Timeline:Page=()=> <Shell n="07" kind="Timeline / Roadmap"><div style={{position:'absolute',inset:'104px 126px 126px'}}><Tag>roadmap</Tag><H size={80} style={{marginTop:28,maxWidth:1200}}>路线图页面负责制造节奏感。</H><div style={{marginTop:62,display:'grid',gridTemplateColumns:'repeat(4,1fr)',gap:18}}>{['Now','Next','Later','Risk'].map((x,i)=><Card key={x} style={{minHeight:330}}><div style={{height:9,width:`${64+i*9}%`,borderRadius:8,background:i===3?'#f59e0b':t.accent}}/><div style={{marginTop:42,fontSize:42,fontWeight:880}}>{x}</div><div style={{marginTop:20,color:t.muted,fontSize:24,lineHeight:1.35}}>{['确定表达场景','沉淀组件','接入生成入口','控制审美漂移'][i]}</div><div style={{marginTop:50,font:`42px ${mono}`,color:t.accent}}>Q{i+1}</div></Card>)}</div></div></Shell>;
const Diagram:Page=()=> <Shell n="08" kind="Diagram / Architecture"><div style={{position:'absolute',inset:'104px 126px 126px',display:'grid',gridTemplateColumns:'.86fr 1.14fr',gap:42,alignItems:'center'}}><div><Tag>diagram</Tag><H size={80} style={{marginTop:28}}>关系复杂时，图比段落诚实。</H><P style={{marginTop:26}}>流程、架构、依赖、分层，都需要默认图形骨架。</P></div><Network/></div></Shell>;
const Closing:Page=()=> <Shell n="09" kind="Closing / CTA"><div style={{position:'absolute',inset:'118px 126px 126px',display:'grid',gridTemplateColumns:'1fr 470px',gap:56,alignItems:'center'}}><div><Tag>ready to reuse</Tag><H size={112} style={{marginTop:34}}>可继续组件化。</H><P style={{marginTop:32,fontSize:36,maxWidth:960}}>{t.short} 已扩展为完整 20 页 template pack。下一步可沉淀为 theme、primitive、recipe。</P></div><Card><div style={{font:`22px ${mono}`,color:t.accent}}>NEXT</div>{['Theme tokens','Slide primitives','Content schema','Screenshot QA'].map((x,i)=><div key={x} style={{display:'grid',gridTemplateColumns:'70px 1fr',gap:14,alignItems:'center',padding:'22px 0',borderBottom:i===3?'none':`1px solid ${t.border}`}}><div style={{font:`24px ${mono}`,color:t.accent}}>0{i+1}</div><div style={{fontSize:34,fontWeight:850}}>{x}</div></div>)}</Card></div></Shell>;

function HeroVisual(){
  if(t.pattern==='launch')return <Launch/>; if(t.pattern==='finance')return <Finance/>; if(t.pattern==='docs')return <Docs/>; if(t.pattern==='carousel')return <Carousel/>; if(t.pattern==='motion')return <Motion/>; if(t.pattern==='magazine')return <Magazine/>; if(t.pattern==='course')return <Course/>; if(t.pattern==='blueprint')return <Blueprint/>; if(t.pattern==='graph')return <Graph/>; if(t.pattern==='terminal')return <Terminal/>; return <Cards/>;
}
function ProblemVisual(){return <div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:20}}>{['Blank page','Random style','Weak story','No QA'].map((x,i)=><Card key={x} style={{height:190}}><div style={{font:`22px ${mono}`,color:t.accent}}>0{i+1}</div><div style={{marginTop:42,fontSize:34,fontWeight:850}}>{x}</div></Card>)}</div>}
function Cards(){return <div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:20}}>{['Tokens','Layouts','Charts','QA'].map((x,i)=><Card key={x} style={{height:220}}><div style={{font:`22px ${mono}`,color:t.accent}}>0{i+1}</div><div style={{marginTop:62,fontSize:44,fontWeight:900,lineHeight:1}}>{x}</div></Card>)}</div>}
function MetricRow(){return <div style={{display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:18}}>{[['9','slides'],['10','new suites'],['0','runtime copied']].map(([a,b])=><Card key={b}><div style={{fontSize:62,lineHeight:1,fontWeight:950,color:t.accent,letterSpacing:'-.06em'}}>{a}</div><div style={{marginTop:12,color:t.muted,fontSize:22}}>{b}</div></Card>)}</div>}
function Bars(){return <Card style={{height:'100%',display:'flex',alignItems:'end',gap:18}}>{[54,92,132,168,214,238].map((h,i)=><div key={i} style={{flex:1,height:h,borderRadius:'18px 18px 0 0',background:i===5?t.accent:rgba(t.accent,.25)}} />)}</Card>}
function Network(){const nodes=[[120,100,'OD'],[405,78,'Tokens'],[650,170,'Layouts'],[270,330,'React'],[585,360,'QA']];return <Card style={{height:500}}><svg viewBox="0 0 780 420" width="100%" height="420">{nodes.slice(1).map((n,i)=><line key={i} x1={nodes[0][0]} y1={nodes[0][1]} x2={n[0]} y2={n[1]} stroke={rgba(t.accent,.62)} strokeWidth="3"/>)}{nodes.map(([x,y,l],i)=><g key={String(l)}><circle cx={Number(x)} cy={Number(y)} r={i?48:64} fill={i?rgba(t.accent,.17):t.accent} stroke={t.accent} strokeWidth="3"/><text x={Number(x)} y={Number(y)+8} textAnchor="middle" fill={i?'currentColor':(dark?'#061014':'#fff')} fontFamily={font()} fontSize="22" fontWeight="850">{l}</text></g>)}</svg></Card>}
function Launch(){return <Card style={{height:520,position:'relative',overflow:'hidden'}}><div style={{position:'absolute',inset:36,borderRadius:34,background:`linear-gradient(135deg,${rgba(t.accent,.18)},transparent)`}}/><div style={{position:'absolute',left:78,top:86,width:300,height:300,borderRadius:58,background:t.accent,boxShadow:`0 38px 90px ${rgba(t.accent,.38)}`}}/><div style={{position:'absolute',right:74,top:78,fontSize:70,fontWeight:950,letterSpacing:'-.07em'}}>Launch</div><div style={{position:'absolute',right:88,bottom:96,width:280,height:12,borderRadius:99,background:t.accent}}/></Card>}
function Finance(){return <Card style={{height:520}}><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:20}}>{['Revenue','Margin','Runway','Risk'].map((x,i)=><div key={x} style={{height:210,borderRadius:24,padding:24,background:rgba(t.accent,i===0?.22:.09),border:`1px solid ${rgba(t.accent,.22)}`}}><div style={{font:`18px ${mono}`,color:t.muted}}>{x}</div><div style={{marginTop:48,fontSize:58,fontWeight:920,color:i===0?t.accent:t.fg}}>{['42%','18%','14M','Low'][i]}</div></div>)}</div></Card>}
function Docs(){return <Card style={{height:520,padding:0,overflow:'hidden'}}><div style={{display:'grid',gridTemplateColumns:'160px 1fr 170px',height:'100%'}}><div style={{padding:24,borderRight:`1px solid ${t.border}`}}>{['Intro','API','Guide','FAQ'].map((x,i)=><div key={x} style={{marginBottom:24,color:i===1?t.accent:t.muted,fontWeight:800}}>{x}</div>)}</div><div style={{padding:34}}><div style={{fontSize:42,fontWeight:900}}>API Reference</div><pre style={{marginTop:30,borderRadius:20,padding:24,background:dark?'#000':'#0f172a',color:'#d1fae5',fontSize:20,lineHeight:1.55}}>{`POST /v1/slides\n{\n  "theme": "docs",\n  "pages": 9\n}`}</pre></div><div style={{padding:24,borderLeft:`1px solid ${t.border}`,color:t.muted}}>On this page<br/>Auth<br/>Schema<br/>Errors</div></div></Card>}
function Carousel(){return <div style={{display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:22}}>{['01','02','03'].map((x,i)=><div key={x} style={{height:500,borderRadius:42,background:['#fff','#ffedd5','#fed7aa'][i],border:`1px solid ${t.border}`,padding:30,transform:`rotate(${[-2,1.3,-1][i]}deg)`,boxShadow:`0 28px 70px ${rgba('#7c2d12',.12)}`}}><div style={{font:`24px ${mono}`,color:t.accent}}>{x}</div><div style={{marginTop:260,fontSize:54,fontWeight:950,lineHeight:.96}}>强标题卡片</div></div>)}</div>}
function Motion(){return <Card style={{height:520}}><div style={{display:'grid',gridTemplateRows:'repeat(3,1fr)',gap:18}}>{['Frame 01','Frame 02','Frame 03'].map((x,i)=><div key={x} style={{height:145,borderRadius:24,border:`1px solid ${rgba(t.accent,.32)}`,background:`linear-gradient(90deg,${rgba(t.accent,.18)},transparent)`,display:'flex',alignItems:'center',padding:'0 28px',gap:24}}><div style={{width:76,height:76,borderRadius:18,background:t.accent,transform:`translateX(${i*34}px)`}}/><div style={{fontSize:34,fontWeight:880}}>{x}</div></div>)}</div></Card>}
function Magazine(){return <Card style={{height:520,display:'grid',gridTemplateColumns:'1fr .72fr',gap:28}}><div><div style={{fontSize:94,lineHeight:.84,letterSpacing:'-.08em',fontWeight:950}}>THE<br/>SYSTEM<br/>ISSUE</div><div style={{marginTop:38,width:220,height:10,background:t.accent}}/></div><div style={{borderLeft:`1px solid ${t.border}`,paddingLeft:28,color:t.muted,fontSize:25,lineHeight:1.38}}>Large editorial headline, restrained body copy, strong cover rhythm.</div></Card>}
function Course(){return <Card style={{height:520}}><div style={{fontSize:42,fontWeight:900}}>Module Path</div><div style={{marginTop:44,display:'grid',gap:18}}>{['Concept','Demo','Practice','Review'].map((x,i)=><div key={x} style={{display:'grid',gridTemplateColumns:'72px 1fr 120px',alignItems:'center',gap:18,padding:22,borderRadius:22,background:rgba(t.accent,.09),border:`1px solid ${rgba(t.accent,.2)}`}}><div style={{font:`24px ${mono}`,color:t.accent}}>0{i+1}</div><div style={{fontSize:32,fontWeight:850}}>{x}</div><div style={{height:10,borderRadius:99,background:i<2?t.accent:rgba(t.accent,.28)}}/></div>)}</div></Card>}
function Blueprint(){return <Card style={{height:520}}><svg viewBox="0 0 760 440" width="100%" height="440">{[80,200,320].map(y=><line key={y} x1="40" y1={y} x2="720" y2={y} stroke={rgba(t.accent,.24)}/>)}{[120,300,480,660].map(x=><line key={x} x1={x} y1="40" x2={x} y2="400" stroke={rgba(t.accent,.18)}/>)}{['Layer A','Layer B','Layer C'].map((x,i)=><g key={x}><rect x={80+i*165} y={90+i*60} width="230" height="92" rx="18" fill={rgba(t.accent,.14)} stroke={t.accent}/><text x={195+i*165} y={145+i*60} textAnchor="middle" fill={t.fg} fontSize="28" fontFamily={font()} fontWeight="850">{x}</text></g>)}</svg></Card>}
function Graph(){const nodes=[[130,130,'Source'],[360,80,'A'],[610,150,'B'],[280,330,'C'],[560,340,'D']];return <Card style={{height:520}}><svg viewBox="0 0 760 440" width="100%" height="440">{[[0,1],[0,2],[1,3],[2,4],[3,4]].map(([a,b],i)=><line key={i} x1={nodes[a][0]} y1={nodes[a][1]} x2={nodes[b][0]} y2={nodes[b][1]} stroke={rgba(t.accent,.7)} strokeWidth="3"/>)}{nodes.map(([x,y,l],i)=><g key={String(l)}><circle cx={Number(x)} cy={Number(y)} r={i?46:62} fill={i?rgba(t.accent,.16):t.accent}/><text x={Number(x)} y={Number(y)+8} textAnchor="middle" fill={i?t.fg:'#05060a'} fontSize="24" fontFamily={font()} fontWeight="900">{l}</text></g>)}</svg></Card>}
function Terminal(){return <Card style={{height:520,padding:0,overflow:'hidden',fontFamily:mono}}><div style={{height:50,display:'flex',alignItems:'center',gap:10,padding:'0 20px',background:rgba(t.accent,.08)}}>{['#00ff99','#fbbf24','#fb7185'].map(c=><span key={c} style={{width:12,height:12,borderRadius:99,background:c}}/>)}<span style={{marginLeft:16,color:t.muted}}>ops@open-slide</span></div><pre style={{margin:0,padding:34,fontSize:24,lineHeight:1.55,color:t.accent}}>{`$ template sync --source open-design\n✓ tokens extracted\n✓ 9 slides generated\n✓ visual qa pending`}</pre></Card>}


const SectionDivider:Page=()=> <Shell n="10" kind="Section Divider"><div style={{position:'absolute',inset:'118px 126px 126px',display:'grid',gridTemplateColumns:'.72fr 1.28fr',gap:56,alignItems:'center'}}><div><Tag>section</Tag><div style={{marginTop:38,font:`42px ${mono}`,color:t.accent}}>PART 02</div></div><div><H size={112}>进入第二组页面。</H><P style={{marginTop:28,fontSize:34}}>用于把长 deck 分段：从叙事流切到案例、细节、附录或执行计划。</P></div></div></Shell>;
const QuoteInsight:Page=()=> <Shell n="11" kind="Quote / Key Insight"><div style={{position:'absolute',inset:'126px 150px',display:'grid',placeItems:'center'}}><Card style={{width:'100%',padding:'70px 82px'}}><div style={{font:`24px ${mono}`,color:t.accent,letterSpacing:'.12em'}}>KEY INSIGHT</div><div style={{marginTop:36,fontSize:78,lineHeight:1.02,letterSpacing:'-.065em',fontWeight:920}}>“模板的价值，是让内容进入正确的表达姿势。”</div><div style={{marginTop:36,color:t.muted,fontSize:28}}>适合放观点、客户 quote、研究结论、章节金句。</div></Card></div></Shell>;
const Comparison:Page=()=> <Shell n="12" kind="Comparison"><div style={{position:'absolute',inset:'104px 126px 126px'}}><Tag>comparison</Tag><H size={80} style={{marginTop:28}}>对比页：把选择压缩成两列判断。</H><div style={{marginTop:52,display:'grid',gridTemplateColumns:'1fr 1fr',gap:28}}>{['Before','After'].map((x,i)=><Card key={x} style={{minHeight:430,borderColor:i?t.accent:t.border}}><div style={{font:`24px ${mono}`,color:t.accent}}>0{i+1}</div><div style={{marginTop:34,fontSize:54,fontWeight:920}}>{x}</div><div style={{marginTop:30,display:'grid',gap:18}}>{['结构','速度','质量'].map((y,j)=><div key={y} style={{display:'grid',gridTemplateColumns:'110px 1fr',gap:14,fontSize:27,color:j===1?t.fg:t.muted}}><b>{y}</b><span>{i?'清晰、可复用':'随机、靠手感'}</span></div>)}</div></Card>)}</div></div></Shell>;
const ProcessWorkflow:Page=()=> <Shell n="13" kind="Process / Workflow"><div style={{position:'absolute',inset:'104px 126px 126px',display:'grid',gridTemplateColumns:'.86fr 1.14fr',gap:44,alignItems:'center'}}><div><Tag>workflow</Tag><H size={80} style={{marginTop:28}}>流程页表达顺序，不表达所有细节。</H><P style={{marginTop:26}}>适合项目流程、用户旅程、调用链、审批链。</P></div><Card style={{height:430}}><svg viewBox="0 0 760 340" width="100%" height="340">{['Input','Plan','Build','Review','Ship'].map((x,i)=><g key={x}><rect x={35+i*145} y={120+(i%2)*26} width="112" height="76" rx="20" fill={rgba(t.accent,.15)} stroke={t.accent}/><text x={91+i*145} y={166+(i%2)*26} textAnchor="middle" fill={t.fg} fontFamily={font()} fontSize="22" fontWeight="850">{x}</text>{i<4&&<line x1={147+i*145} y1={158+(i%2)*26} x2={180+i*145} y2={158+((i+1)%2)*26} stroke={t.accent} strokeWidth="4"/>}</g>)}</svg></Card></div></Shell>;
const Matrix2x2:Page=()=> <Shell n="14" kind="Matrix / 2×2"><div style={{position:'absolute',inset:'104px 126px 126px'}}><Tag>matrix</Tag><H size={78} style={{marginTop:28}}>二维矩阵：把讨论从争论变成定位。</H><Card style={{marginTop:42,height:500,position:'relative'}}><div style={{position:'absolute',left:90,right:90,top:250,height:2,background:t.border}}/><div style={{position:'absolute',top:70,bottom:70,left:'50%',width:2,background:t.border}}/>{[['Quick Win',180,125],['Strategic',520,115],['Avoid',190,345],['Experiment',530,350]].map(([x,l,top],i)=><div key={String(x)} style={{position:'absolute',left:Number(l)-80,top:Number(top)-45,width:190,height:82,borderRadius:24,background:i===1?t.accent:rgba(t.accent,.14),display:'grid',placeItems:'center',fontSize:24,fontWeight:900,color:i===1?(dark?'#061014':'#fff'):t.fg}}>{x}</div>)}</Card></div></Shell>;
const TableSpec:Page=()=> <Shell n="15" kind="Table / Spec"><div style={{position:'absolute',inset:'104px 126px 126px'}}><Tag>table</Tag><H size={78} style={{marginTop:28}}>规格表：让信息可查，不靠段落解释。</H><Card style={{marginTop:44,padding:0,overflow:'hidden'}}><table style={{width:'100%',borderCollapse:'collapse',fontSize:25}}><tbody>{[['Item','Owner','Status','Note'],['Scope','PM','Ready','v1 only'],['Design','Design','Review','2 variants'],['Build','Eng','Doing','API first'],['QA','Ops','Next','screenshot gate']].map((r,i)=><tr key={i}>{r.map((c,j)=><td key={j} style={{padding:'22px 26px',borderBottom:`1px solid ${t.border}`,color:i===0?t.accent:t.fg,fontWeight:i===0?900:j===0?850:520,background:i===0?rgba(t.accent,.08):'transparent'}}>{c}</td>)}</tr>)}</tbody></table></Card></div></Shell>;
const CaseStudy:Page=()=> <Shell n="16" kind="Case Study"><div style={{position:'absolute',inset:'104px 126px 126px',display:'grid',gridTemplateColumns:'1.04fr .96fr',gap:42,alignItems:'center'}}><div><Tag>case study</Tag><H size={82} style={{marginTop:28}}>案例页要讲变化。</H><P style={{marginTop:26}}>背景、动作、结果三段式；适合客户案例、内部复盘、项目样板。</P><div style={{marginTop:36,display:'flex',gap:14}}>{['Context','Action','Result'].map(x=><Tag key={x}>{x}</Tag>)}</div></div><Card style={{height:460}}><div style={{font:`22px ${mono}`,color:t.accent}}>RESULT</div><div style={{marginTop:36,fontSize:84,lineHeight:1,fontWeight:950,color:t.accent}}>3.4×</div><div style={{marginTop:28,color:t.muted,fontSize:28,lineHeight:1.35}}>更快完成同类交付，同时保留可复用结构。</div><Bars/></Card></div></Shell>;
const ChecklistPage:Page=()=> <Shell n="17" kind="Checklist"><div style={{position:'absolute',inset:'104px 126px 126px',display:'grid',gridTemplateColumns:'.82fr 1.18fr',gap:42,alignItems:'center'}}><div><Tag>checklist</Tag><H size={80} style={{marginTop:28}}>清单页负责把行动变明确。</H><P style={{marginTop:26}}>不要写大段建议。让观众知道下一步检查什么。</P></div><div style={{display:'grid',gap:16}}>{['目标是否单一','指标是否可量化','风险是否有人负责','交付物是否可验收','下一步是否明确'].map((x,i)=><Card key={x} style={{display:'grid',gridTemplateColumns:'60px 1fr',alignItems:'center',gap:16,padding:24}}><div style={{width:36,height:36,borderRadius:99,background:t.accent,color:dark?'#061014':'#fff',display:'grid',placeItems:'center',font:`20px ${mono}`}}>✓</div><div style={{fontSize:30,fontWeight:850}}>{x}</div></Card>)}</div></div></Shell>;
const RisksTradeoffs:Page=()=> <Shell n="18" kind="Risks / Tradeoffs"><div style={{position:'absolute',inset:'104px 126px 126px'}}><Tag>risks</Tag><H size={78} style={{marginTop:28}}>风险页不吓人，风险页要分配动作。</H><div style={{marginTop:50,display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:22}}>{[['Risk','可能发生什么'],['Impact','影响有多大'],['Mitigation','谁来处理']].map(([a,b],i)=><Card key={a} style={{minHeight:360,borderColor:i===0?'#ef4444':i===2?t.accent:t.border}}><div style={{font:`22px ${mono}`,color:i===0?'#ef4444':t.accent}}>0{i+1}</div><div style={{marginTop:36,fontSize:46,fontWeight:920}}>{a}</div><div style={{marginTop:24,fontSize:26,lineHeight:1.36,color:t.muted}}>{b}</div></Card>)}</div></div></Shell>;
const FAQAppendix:Page=()=> <Shell n="19" kind="FAQ / Appendix"><div style={{position:'absolute',inset:'104px 126px 126px'}}><Tag>appendix</Tag><H size={78} style={{marginTop:28}}>附录页不是垃圾桶，是可查证的答案库。</H><div style={{marginTop:44,display:'grid',gap:16}}>{['为什么选择这套结构？','哪些内容可以删掉？','如何适配长报告？','如何进入下一步？'].map((q,i)=><Card key={q} style={{display:'grid',gridTemplateColumns:'70px 1fr',gap:18,alignItems:'center'}}><div style={{font:`25px ${mono}`,color:t.accent}}>Q{i+1}</div><div style={{fontSize:30,fontWeight:850}}>{q}</div></Card>)}</div></div></Shell>;
const ThankYou:Page=()=> <Shell n="20" kind="Thank You / Contact"><div style={{position:'absolute',inset:'118px 126px 126px',display:'grid',gridTemplateColumns:'1fr 460px',gap:56,alignItems:'center'}}><div><Tag>template pack</Tag><H size={114} style={{marginTop:34}}>20 页模板包。</H><P style={{marginTop:32,fontSize:36,maxWidth:940}}>前 9 页覆盖基础叙事，后 11 页覆盖常见子页面。保持风格，不乱拆。</P></div><Card><div style={{font:`22px ${mono}`,color:t.accent}}>PAGES</div>{['01–09 Base flow','10–16 Extended recipes','17–20 Action / appendix'].map((x,i)=><div key={x} style={{padding:'26px 0',borderBottom:i===2?'none':`1px solid ${t.border}`,fontSize:30,fontWeight:850}}>{x}</div>)}</Card></div></Shell>;

export default [Cover,Agenda,Problem,Framework,Content,Metrics,Timeline,Diagram,Closing,SectionDivider,QuoteInsight,Comparison,ProcessWorkflow,Matrix2x2,TableSpec,CaseStudy,ChecklistPage,RisksTradeoffs,FAQAppendix,ThankYou];
