import type { CSSProperties, ReactNode } from 'react';
import type { DesignSystem, Page, SlideMeta } from '@open-slide/core';

type Theme = { slug:string; title:string; short:string; source:string; best:string; tone:string; bg:string; fg:string; muted:string; accent:string; card:string; border:string; font:'serif'|'sans'|'mono'; pattern:string };
const t = {"slug": "od-kami-paper-suite", "title": "OD Kami Paper Suite", "short": "Kami Paper", "source": "Open Design: skills/kami-deck + design-systems/kami", "best": "研究报告 / Repo Explainer / AI 日报", "tone": "暖纸、墨蓝、衬线、克制", "bg": "#f5f4ed", "fg": "#141413", "muted": "#68655e", "accent": "#1B365D", "card": "#faf9f5", "border": "#e4e0d2", "font": "serif", "pattern": "paper"} as Theme;
const serif='Georgia, "Noto Serif CJK SC", "Source Han Serif SC", "Songti SC", serif';
const sans='Inter, "PingFang SC", "Microsoft YaHei", system-ui, sans-serif';
const mono='"JetBrains Mono", ui-monospace, SFMono-Regular, Menlo, Consolas, monospace';
const font=()=>t.font==='serif'?serif:t.font==='mono'?mono:sans;
const rgba=(h:string,a:number)=>{const x=h.replace('#','');const n=parseInt(x.length===3?x.split('').map(c=>c+c).join(''):x,16);return `rgba(${(n>>16)&255}, ${(n>>8)&255}, ${n&255}, ${a})`;};
const isDarkBg=(h:string)=>{const x=h.replace('#','');const n=parseInt(x.length===3?x.split('').map(c=>c+c).join(''):x,16);const r=(n>>16)&255,g=(n>>8)&255,b=n&255;return (0.2126*r+0.7152*g+0.0722*b)<96};
const dark=isDarkBg(t.bg);
const base:CSSProperties={width:'100%',height:'100%',position:'relative',overflow:'hidden',boxSizing:'border-box',background:t.bg,color:t.fg,fontFamily:font()};

export const design: DesignSystem = { palette:{bg:t.bg,text:t.fg,accent:t.accent}, fonts:{display:font(),body:font()}, typeScale:{hero:110,body:30}, radius:28 };
export const meta: SlideMeta = { title:t.title, description:`${t.short} 独立 Open-Slide 模板套件：20 个常见 PPT page templates。` };
export const notes = [`${t.short} standalone album`, '只移植 Open Design 视觉语言，不复制 runtime。', '20 页覆盖常见 PPT 页面类型。'];

const css=`@keyframes rise{from{opacity:0;transform:translateY(24px)}to{opacity:1;transform:translateY(0)}}@keyframes spin{to{transform:rotate(360deg)}}@keyframes pulse{0%,100%{opacity:.55;transform:scale(.94)}50%{opacity:1;transform:scale(1.05)}}.r{animation:rise .62s cubic-bezier(.2,.9,.2,1) both}.card{border-radius:30px;border:1.5px solid ${t.border};background:${t.card};box-shadow:0 24px 70px ${rgba(t.fg,.08)}}.tag{display:inline-flex;border-radius:999px;padding:10px 16px;font:800 18px/1 ${mono};letter-spacing:.1em;text-transform:uppercase}`;
function Shell({n,kind,children}:{n:string;kind:string;children:ReactNode}){return <div style={base}><style>{css}</style><Decor/><div style={{position:'absolute',inset:52,border:`1px solid ${rgba(t.fg,.12)}`,borderRadius:36,pointerEvents:'none'}}/>{children}<div style={{position:'absolute',left:86,bottom:64,color:t.muted,font:`18px ${mono}`,letterSpacing:'.08em'}}>{n} · {kind}</div><div style={{position:'absolute',right:86,bottom:64,color:t.muted,font:`18px ${mono}`}}>{t.short} · Open Design → Open Slide</div></div>}
function Tag({children}:{children:ReactNode}){return <span className="tag" style={{background:rgba(t.accent,.15),color:t.accent,border:`1px solid ${rgba(t.accent,.26)}`}}>{children}</span>}
function H({children,size=92,style}:{children:ReactNode;size?:number;style?:CSSProperties}){return <h1 className="r" style={{margin:0,fontSize:size,lineHeight:.94,letterSpacing:'-.065em',fontWeight:850,color:t.fg,...style}}>{children}</h1>}
function P({children,style}:{children:ReactNode;style?:CSSProperties}){return <p className="r" style={{margin:0,color:t.muted,fontSize:30,lineHeight:1.38,...style}}>{children}</p>}
function Card({children,style}:{children:ReactNode;style?:CSSProperties}){return <div className="card r" style={{padding:32,...style}}>{children}</div>}
function Decor(){const dark=['atlas','tech'].includes(t.pattern);return <div style={{position:'absolute',right:-150,top:-150,width:520,height:520,borderRadius:999,background:dark?`radial-gradient(circle, ${rgba(t.accent,.30)}, transparent 66%)`:rgba(t.accent,.10)}}/>}

const Cover:Page=()=> <Shell n="01" kind="Cover"><div style={{position:'absolute',inset:'112px 126px 126px',display:'grid',gridTemplateColumns:'1.05fr .95fr',gap:56,alignItems:'center'}}><div><Tag>{t.source}</Tag><H size={126} style={{marginTop:34,maxWidth:1000}}>{t.short}</H><P style={{marginTop:34,fontSize:38,maxWidth:900}}>{t.best}</P><div style={{marginTop:44,display:'flex',gap:14,flexWrap:'wrap'}}>{['20 pages','template pack','React primitives'].map(x=><Tag key={x}>{x}</Tag>)}</div></div><HeroVisual/></div></Shell>;
const Agenda:Page=()=> <Shell n="02" kind="Agenda"><div style={{position:'absolute',inset:'104px 126px 126px'}}><Tag>common ppt formats</Tag><H size={82} style={{marginTop:28,maxWidth:1180}}>一套模板覆盖二十种常见页面。</H><div style={{marginTop:46,display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:20}}>{['Cover','Agenda','Problem','Framework','Content','Metrics','Timeline','Diagram','Closing'].map((x,i)=><Card key={x} style={{minHeight:142,animationDelay:`${i*35}ms`}}><div style={{font:`21px ${mono}`,color:t.accent}}>0{i+1}</div><div style={{marginTop:22,fontSize:34,fontWeight:850}}>{x}</div></Card>)}</div></div></Shell>;
const Problem:Page=()=> <Shell n="03" kind="Problem / Context"><div style={{position:'absolute',inset:'104px 126px 126px',display:'grid',gridTemplateColumns:'.9fr 1.1fr',gap:46,alignItems:'center'}}><div><Tag>why this template</Tag><H size={86} style={{marginTop:30}}>模板不是皮肤，是降低表达成本。</H><P style={{marginTop:28}}>每次从空白页开始，Agent 会浪费大量精力在随机排版。模板套件让内容先进入成熟结构。</P></div><ProblemVisual/></div></Shell>;
const Framework:Page=()=> <Shell n="04" kind="Framework"><div style={{position:'absolute',inset:'104px 126px 126px'}}><Tag>framework</Tag><H size={82} style={{marginTop:28,maxWidth:1240}}>三层融合：视觉语料、页面范式、生产约束。</H><div style={{marginTop:56,display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:24}}>{[['01','Tokens','颜色、字体、圆角、边框、强调比例。'],['02','Archetypes','封面、内容、指标、流程、图解、收尾。'],['03','QA','截图验收，避免溢出、拥挤、低级 PPT 感。']].map(([a,b,c],i)=><Card key={b} style={{minHeight:330,animationDelay:`${i*70}ms`}}><div style={{font:`22px ${mono}`,color:t.accent}}>{a}</div><h2 style={{fontSize:48,lineHeight:1.05,margin:'34px 0 18px',letterSpacing:'-.05em'}}>{b}</h2><p style={{fontSize:26,lineHeight:1.38,color:t.muted,margin:0}}>{c}</p></Card>)}</div></div></Shell>;
const Content:Page=()=> <Shell n="05" kind="Content"><div style={{position:'absolute',inset:'104px 126px 126px',display:'grid',gridTemplateColumns:'1fr 1fr',gap:42,alignItems:'center'}}><div><Tag>content slide</Tag><H size={84} style={{marginTop:30}}>左侧结论，右侧证据。</H><P style={{marginTop:28}}>这是最常用的业务 PPT 页面：一个判断 + 三条证据 + 一个轻量图形。</P></div><div style={{display:'grid',gap:18}}>{['先给结论，别让观众猜。','证据用卡片分层，最多三组。','强调色只点亮关键路径。'].map((x,i)=><Card key={x} style={{display:'grid',gridTemplateColumns:'72px 1fr',gap:18,alignItems:'center'}}><div style={{font:`28px ${mono}`,color:t.accent}}>0{i+1}</div><div style={{fontSize:31,lineHeight:1.25,color:t.fg}}>{x}</div></Card>)}</div></div></Shell>;
const Metrics:Page=()=> <Shell n="06" kind="Metrics / Data"><div style={{position:'absolute',inset:'104px 126px 126px',display:'grid',gridTemplateColumns:'.85fr 1.15fr',gap:44,alignItems:'center'}}><div><Tag>metrics</Tag><H size={82} style={{marginTop:28}}>数据页必须带判断。</H><P style={{marginTop:26}}>指标、趋势、风险、下一步，要在同一页完成闭环。</P></div><div><MetricRow/><div style={{height:260,marginTop:24}}><Bars/></div></div></div></Shell>;
const Timeline:Page=()=> <Shell n="07" kind="Timeline / Roadmap"><div style={{position:'absolute',inset:'104px 126px 126px'}}><Tag>timeline</Tag><H size={82} style={{marginTop:28,maxWidth:1200}}>时间线页面负责表达节奏和承诺。</H><div style={{marginTop:62,display:'grid',gridTemplateColumns:'repeat(4,1fr)',gap:18}}>{['Now','Next','Later','Risk'].map((x,i)=><Card key={x} style={{minHeight:330}}><div style={{height:9,width:`${64+i*9}%`,borderRadius:8,background:i===3?'#f59e0b':t.accent}}/><div style={{marginTop:42,fontSize:42,fontWeight:850}}>{x}</div><div style={{marginTop:20,color:t.muted,fontSize:24,lineHeight:1.35}}>{['确认模板方向','抽组件和 recipe','接入创建流程','控制审美漂移'][i]}</div><div style={{marginTop:50,font:`42px ${mono}`,color:t.accent}}>Q{i+1}</div></Card>)}</div></div></Shell>;
const Diagram:Page=()=> <Shell n="08" kind="Diagram / Architecture"><div style={{position:'absolute',inset:'104px 126px 126px',display:'grid',gridTemplateColumns:'.86fr 1.14fr',gap:42,alignItems:'center'}}><div><Tag>diagram</Tag><H size={82} style={{marginTop:28}}>复杂关系要图形化，不堆段落。</H><P style={{marginTop:26}}>架构图、流程图、层级图都应该是模板默认能力。</P></div><Network/></div></Shell>;
const Closing:Page=()=> <Shell n="09" kind="Closing / CTA"><div style={{position:'absolute',inset:'118px 126px 126px',display:'grid',gridTemplateColumns:'1fr 470px',gap:56,alignItems:'center'}}><div><Tag>ready to use</Tag><H size={118} style={{marginTop:34}}>这才像一个 album。</H><P style={{marginTop:32,fontSize:36,maxWidth:960}}>{t.short} 已具备完整 PPT 常用页面骨架，可继续沉淀为主题、组件和生成 recipe。</P></div><Card><div style={{font:`22px ${mono}`,color:t.accent}}>NEXT</div>{['Theme tokens','Page primitives','Content schema','Screenshot QA'].map((x,i)=><div key={x} style={{display:'grid',gridTemplateColumns:'70px 1fr',gap:14,alignItems:'center',padding:'22px 0',borderBottom:i===3?'none':`1px solid ${t.border}`}}><div style={{font:`24px ${mono}`,color:t.accent}}>0{i+1}</div><div style={{fontSize:34,fontWeight:850}}>{x}</div></div>)}</Card></div></Shell>;

function HeroVisual(){if(t.pattern==='xhs')return <XhsCards/>; if(t.pattern==='dashboard')return <Dashboard/>; if(t.pattern==='tech')return <Code/>; if(t.pattern==='atlas')return <Network/>; return <Cards/>}
function ProblemVisual(){return <div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:20}}>{['Blank page','Random layout','Weak hierarchy','No QA'].map((x,i)=><Card key={x} style={{height:190}}><div style={{font:`22px ${mono}`,color:t.accent}}>0{i+1}</div><div style={{marginTop:42,fontSize:34,fontWeight:850}}>{x}</div></Card>)}</div>}
function Cards(){return <div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:20}}>{['Tokens','Layouts','Charts','QA'].map((x,i)=><Card key={x} style={{height:220}}><div style={{font:`22px ${mono}`,color:t.accent}}>0{i+1}</div><div style={{marginTop:62,fontSize:44,fontWeight:900,lineHeight:1}}>{x}</div></Card>)}</div>}
function MetricRow(){return <div style={{display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:18}}>{[['20','pages'],['11','recipes'],['0','runtime copied']].map(([a,b])=><Card key={b}><div style={{fontSize:62,lineHeight:1,fontWeight:950,color:t.accent,letterSpacing:'-.06em'}}>{a}</div><div style={{marginTop:12,color:t.muted,fontSize:22}}>{b}</div></Card>)}</div>}
function Bars(){return <Card style={{height:'100%',display:'flex',alignItems:'end',gap:18}}>{[42,76,112,146,190,228].map((h,i)=><div key={i} style={{flex:1,height:h,borderRadius:'18px 18px 0 0',background:i===5?t.accent:rgba(t.accent,.24)}} />)}</Card>}
function Network(){const nodes=[[120,100,'Open Design'],[405,78,'Tokens'],[650,170,'Archetypes'],[270,330,'React'],[585,360,'QA']];return <Card style={{height:500}}><svg viewBox="0 0 780 420" width="100%" height="420">{nodes.slice(1).map((n,i)=><line key={i} x1={nodes[0][0]} y1={nodes[0][1]} x2={n[0]} y2={n[1]} stroke={rgba(t.accent,.62)} strokeWidth="3"/>)}{nodes.map(([x,y,l],i)=><g key={String(l)}><circle cx={Number(x)} cy={Number(y)} r={i?48:64} fill={i?rgba(t.accent,.17):t.accent} stroke={t.accent} strokeWidth="3"/><text x={Number(x)} y={Number(y)+8} textAnchor="middle" fill={i?'currentColor':'#fff'} fontFamily={font()} fontSize="22" fontWeight="850">{l}</text></g>)}</svg></Card>}
function Dashboard(){return <Card style={{padding:0,overflow:'hidden'}}><div style={{display:'grid',gridTemplateColumns:'170px 1fr',height:500}}><div style={{background:'#111827',color:'#fff',padding:24}}><div style={{fontSize:28,fontWeight:850}}>OD</div>{['Home','Metrics','Users','Logs'].map((x,i)=><div key={x} style={{marginTop:28,color:i===1?'#fff':'#aab2c0'}}>{x}</div>)}</div><div style={{padding:28}}><MetricRow/><div style={{height:230,marginTop:20}}><Bars/></div></div></div></Card>}
function XhsCards(){return <div style={{display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:22}}>{['封面','观点','收藏'].map((x,i)=><div key={x} style={{height:500,borderRadius:38,background:['#fff0f3','#f0f7ff','#fff8e6'][i],border:`1px solid ${t.border}`,padding:28,transform:`rotate(${[-2,1.5,-1][i]}deg)`}}><div style={{height:12,borderRadius:9,background:'linear-gradient(90deg,#ff6b6b,#ffd166,#06d6a0,#118ab2,#9b5de5)'}}/><div style={{marginTop:250,fontSize:58,fontWeight:950,lineHeight:.95}}>{x}</div><div style={{marginTop:18,color:t.muted,fontSize:22}}>强标题 + 软卡片</div></div>)}</div>}
function Code(){return <Card style={{padding:0,overflow:'hidden',fontFamily:mono}}><div style={{height:46,display:'flex',alignItems:'center',gap:8,padding:'0 18px',background:rgba(t.fg,.08)}}>{['#ff5f57','#ffbd2e','#28c840'].map(c=><span key={c} style={{width:12,height:12,borderRadius:99,background:c}}/>)}<span style={{marginLeft:14,color:t.muted}}>template.ts</span></div><pre style={{margin:0,padding:34,fontSize:24,lineHeight:1.55}}>{`export const album = {\n  pages: 9,\n  runtime: "Open Slide",\n  source: "Open Design"\n}`}</pre></Card>}

const SectionDivider:Page=()=> <Shell n="10" kind="Section Divider"><div style={{position:'absolute',inset:'118px 126px 126px',display:'grid',gridTemplateColumns:'.72fr 1.28fr',gap:56,alignItems:'center'}}><div><Tag>section</Tag><div style={{marginTop:38,font:`42px ${mono}`,color:t.accent}}>PART 02</div></div><div><H size={112}>进入第二组页面。</H><P style={{marginTop:28,fontSize:34}}>用于把长 deck 分段：从叙事流切到案例、细节、附录或执行计划。</P></div></div></Shell>;
const QuoteInsight:Page=()=> <Shell n="11" kind="Quote / Key Insight"><div style={{position:'absolute',inset:'126px 150px',display:'grid',placeItems:'center'}}><Card style={{width:'100%',padding:'70px 82px'}}><div style={{font:`24px ${mono}`,color:t.accent,letterSpacing:'.12em'}}>KEY INSIGHT</div><div style={{marginTop:36,fontSize:78,lineHeight:1.02,letterSpacing:'-.065em',fontWeight:920}}>“模板的价值，是让内容进入正确的表达姿势。”</div><div style={{marginTop:36,color:t.muted,fontSize:28}}>适合放观点、客户 quote、研究结论、章节金句。</div></Card></div></Shell>;
const Comparison:Page=()=> <Shell n="12" kind="Comparison"><div style={{position:'absolute',inset:'104px 126px 126px'}}><Tag>comparison</Tag><H size={80} style={{marginTop:28}}>对比页：把选择压缩成两列判断。</H><div style={{marginTop:52,display:'grid',gridTemplateColumns:'1fr 1fr',gap:28}}>{['Before','After'].map((x,i)=><Card key={x} style={{minHeight:430,borderColor:i?t.accent:t.border}}><div style={{font:`24px ${mono}`,color:t.accent}}>0{i+1}</div><div style={{marginTop:34,fontSize:54,fontWeight:920}}>{x}</div><div style={{marginTop:30,display:'grid',gap:18}}>{['结构','速度','质量'].map((y,j)=><div key={y} style={{display:'grid',gridTemplateColumns:'110px 1fr',gap:14,fontSize:27,color:j===1?t.fg:t.muted}}><b>{y}</b><span>{i?'清晰、可复用':'随机、靠手感'}</span></div>)}</div></Card>)}</div></div></Shell>;
const ProcessWorkflow:Page=()=> <Shell n="13" kind="Process / Workflow"><div style={{position:'absolute',inset:'104px 126px 126px',display:'grid',gridTemplateColumns:'.86fr 1.14fr',gap:44,alignItems:'center'}}><div><Tag>workflow</Tag><H size={80} style={{marginTop:28}}>流程页表达顺序，不表达所有细节。</H><P style={{marginTop:26}}>适合项目流程、用户旅程、调用链、审批链。</P></div><Card style={{height:430}}><svg viewBox="0 0 760 340" width="100%" height="340">{['Input','Plan','Build','Review','Ship'].map((x,i)=><g key={x}><rect x={35+i*145} y={120+(i%2)*26} width="112" height="76" rx="20" fill={rgba(t.accent,.15)} stroke={t.accent}/><text x={91+i*145} y={166+(i%2)*26} textAnchor="middle" fill={t.fg} fontFamily={font()} fontSize="22" fontWeight="850">{x}</text>{i<4&&<line x1={147+i*145} y1={158+(i%2)*26} x2={180+i*145} y2={158+((i+1)%2)*26} stroke={t.accent} strokeWidth="4"/>}</g>)}</svg></Card></div></Shell>;
const Matrix2x2:Page=()=> <Shell n="14" kind="Matrix / 2×2"><div style={{position:'absolute',inset:'104px 126px 126px'}}><Tag>matrix</Tag><H size={78} style={{marginTop:28}}>二维矩阵：把讨论从争论变成定位。</H><Card style={{marginTop:42,height:500,position:'relative'}}><div style={{position:'absolute',left:90,right:90,top:250,height:2,background:t.border}}/><div style={{position:'absolute',top:70,bottom:70,left:'50%',width:2,background:t.border}}/>{[['Quick Win',180,125],['Strategic',520,115],['Avoid',190,345],['Experiment',530,350]].map(([x,l,top],i)=><div key={String(x)} style={{position:'absolute',left:Number(l)-80,top:Number(top)-45,width:190,height:82,borderRadius:24,background:i===1?t.accent:rgba(t.accent,.14),display:'grid',placeItems:'center',fontSize:24,fontWeight:900,color:i===1?(dark?'#061014':'#fff'):t.fg}}>{x}</div>)}</Card></div></Shell>;
const TableSpec:Page=()=> <Shell n="15" kind="Table / Spec"><div style={{position:'absolute',inset:'104px 126px 126px'}}><Tag>table</Tag><H size={78} style={{marginTop:28}}>规格表：让信息可查，不靠段落解释。</H><Card style={{marginTop:44,padding:0,overflow:'hidden'}}><table style={{width:'100%',borderCollapse:'collapse',fontSize:25}}><tbody>{[['Item','Owner','Status','Note'],['Scope','PM','Ready','v1 only'],['Design','Design','Review','2 variants'],['Build','Eng','Doing','API first'],['QA','Ops','Next','screenshot gate']].map((r,i)=><tr key={i}>{r.map((c,j)=><td key={j} style={{padding:'22px 26px',borderBottom:`1px solid ${t.border}`,color:i===0?t.accent:t.fg,fontWeight:i===0?900:j===0?850:520,background:i===0?rgba(t.accent,.08):'transparent'}}>{c}</td>)}</tr>)}</tbody></table></Card></div></Shell>;
const CaseStudy:Page=()=> <Shell n="16" kind="Case Study"><div style={{position:'absolute',inset:'104px 126px 126px',display:'grid',gridTemplateColumns:'1.04fr .96fr',gap:42,alignItems:'center'}}><div><Tag>case study</Tag><H size={82} style={{marginTop:28}}>案例页要讲变化。</H><P style={{marginTop:26}}>背景、动作、结果三段式；适合客户案例、内部复盘、项目样板。</P><div style={{marginTop:36,display:'flex',gap:14}}>{['Context','Action','Result'].map(x=><Tag key={x}>{x}</Tag>)}</div></div><Card style={{height:460}}><div style={{font:`22px ${mono}`,color:t.accent}}>RESULT</div><div style={{marginTop:36,fontSize:84,lineHeight:1,fontWeight:950,color:t.accent}}>3.4×</div><div style={{marginTop:28,color:t.muted,fontSize:28,lineHeight:1.35}}>更快完成同类交付，同时保留可复用结构。</div><Bars/></Card></div></Shell>;
const ChecklistPage:Page=()=> <Shell n="17" kind="Checklist"><div style={{position:'absolute',inset:'104px 126px 126px',display:'grid',gridTemplateColumns:'.82fr 1.18fr',gap:42,alignItems:'center'}}><div><Tag>checklist</Tag><H size={80} style={{marginTop:28}}>清单页负责把行动变明确。</H><P style={{marginTop:26}}>不要写大段建议。让观众知道下一步检查什么。</P></div><div style={{display:'grid',gap:16}}>{['目标是否单一','指标是否可量化','风险是否有人负责','交付物是否可验收','下一步是否明确'].map((x,i)=><Card key={x} style={{display:'grid',gridTemplateColumns:'60px 1fr',alignItems:'center',gap:16,padding:24}}><div style={{width:36,height:36,borderRadius:99,background:t.accent,color:dark?'#061014':'#fff',display:'grid',placeItems:'center',font:`20px ${mono}`}}>✓</div><div style={{fontSize:30,fontWeight:850}}>{x}</div></Card>)}</div></div></Shell>;
const RisksTradeoffs:Page=()=> <Shell n="18" kind="Risks / Tradeoffs"><div style={{position:'absolute',inset:'104px 126px 126px'}}><Tag>risks</Tag><H size={78} style={{marginTop:28}}>风险页不吓人，风险页要分配动作。</H><div style={{marginTop:50,display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:22}}>{[['Risk','可能发生什么'],['Impact','影响有多大'],['Mitigation','谁来处理']].map(([a,b],i)=><Card key={a} style={{minHeight:360,borderColor:i===0?'#ef4444':i===2?t.accent:t.border}}><div style={{font:`22px ${mono}`,color:i===0?'#ef4444':t.accent}}>0{i+1}</div><div style={{marginTop:36,fontSize:46,fontWeight:920}}>{a}</div><div style={{marginTop:24,fontSize:26,lineHeight:1.36,color:t.muted}}>{b}</div></Card>)}</div></div></Shell>;
const FAQAppendix:Page=()=> <Shell n="19" kind="FAQ / Appendix"><div style={{position:'absolute',inset:'104px 126px 126px'}}><Tag>appendix</Tag><H size={78} style={{marginTop:28}}>附录页不是垃圾桶，是可查证的答案库。</H><div style={{marginTop:44,display:'grid',gap:16}}>{['为什么选择这套结构？','哪些内容可以删掉？','如何适配长报告？','如何进入下一步？'].map((q,i)=><Card key={q} style={{display:'grid',gridTemplateColumns:'70px 1fr',gap:18,alignItems:'center'}}><div style={{font:`25px ${mono}`,color:t.accent}}>Q{i+1}</div><div style={{fontSize:30,fontWeight:850}}>{q}</div></Card>)}</div></div></Shell>;
const ThankYou:Page=()=> <Shell n="20" kind="Thank You / Contact"><div style={{position:'absolute',inset:'118px 126px 126px',display:'grid',gridTemplateColumns:'1fr 460px',gap:56,alignItems:'center'}}><div><Tag>template pack</Tag><H size={114} style={{marginTop:34}}>20 页模板包。</H><P style={{marginTop:32,fontSize:36,maxWidth:940}}>前 9 页覆盖基础叙事，后 11 页覆盖常见子页面。保持风格，不乱拆。</P></div><Card><div style={{font:`22px ${mono}`,color:t.accent}}>PAGES</div>{['01–09 Base flow','10–16 Extended recipes','17–20 Action / appendix'].map((x,i)=><div key={x} style={{padding:'26px 0',borderBottom:i===2?'none':`1px solid ${t.border}`,fontSize:30,fontWeight:850}}>{x}</div>)}</Card></div></Shell>;

export default [Cover,Agenda,Problem,Framework,Content,Metrics,Timeline,Diagram,Closing,SectionDivider,QuoteInsight,Comparison,ProcessWorkflow,Matrix2x2,TableSpec,CaseStudy,ChecklistPage,RisksTradeoffs,FAQAppendix,ThankYou];
